language: node_js
sudo: false
node_js:
  - '5.5.0'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm config set progress=false
  - npm config set spin=false
script:
  - npm run check
