apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: starboard-job-server-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: starboard-job-server
        environment: production
    spec:
      restartPolicy: Always
      volumes:
        - name: secret-volume
          secret:
            secretName: starboard-secret-prod
      containers:
        - name: starboard-job-server-container
          image: us.gcr.io/starboard-1224/starboard-job-server:v13
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: /etc/secret-volume
