FROM daiweilu/starboard-job-server-node-modules:v<%= baseimage_version %>

# Add package.json again to include up to date version
ADD job-server/package.json /app/
RUN npm install

ADD job-server/config /app/config
ADD job-server/src /app/src

CMD ["node", "--harmony_destructuring", "--harmony_default_parameters", "src/index.js"]
