FROM daiweilu/starboard-http-server-node-modules:v<%= baseimage_version %>

# Add package.json again to include up to date version
ADD http-server/package.json /app/

ADD http-server/src /app/src
ADD http-server/config /app/config
ADD http-server/template /app/template
ADD http-server/static /app/static

EXPOSE 10000
CMD ["node", "--harmony_destructuring", "--harmony_default_parameters", "src/index.js"]
