FROM daiweilu/starboard-job-server-node-modules:v<%= baseimage_version %>

ENV NODE_ENV production

# Add application code
ADD build /job-server/build
ADD config /job-server/config

WORKDIR /job-server

CMD ["node", "build/delayed-job.js"]
