FROM daiweilu/starboard-node-modules:v<%= baseimage_version %>

ADD package.json /app/

ADD build /app/build
ADD config /app/config
ADD template /app/template
ADD public /app/public
ADD static /app/static

EXPOSE 10000
CMD ["node", "build/server.js"]
