FROM daiweilu/starboard-job-server-node-modules:v<%= baseimage_version %>

ADD shared-backend/log /shared-backend/log
ADD shared-backend/model /shared-backend/model
ADD shared-backend/db.js /shared-backend/db.js
ADD shared-backend/github.js /shared-backend/github.js
ADD shared-backend/pubsub.js /shared-backend/pubsub.js
ADD shared-backend/redis.js /shared-backend/redis.js

# Add package.json again to include up to date version
ADD job-server/package.json /app/

ADD job-server/config /app/config
ADD job-server/src /app/src

CMD ["node", "--harmony_destructuring", "--harmony_default_parameters", "src/index.js"]
