FROM daiweilu/starboard-http-server-node-modules:v<%= baseimage_version %>

ADD shared-backend/log /shared-backend/log
ADD shared-backend/model /shared-backend/model
ADD shared-backend/db.js /shared-backend/db.js
ADD shared-backend/github.js /shared-backend/github.js
ADD shared-backend/pubsub.js /shared-backend/pubsub.js
ADD shared-backend/redis.js /shared-backend/redis.js

RUN mkdir /shared
ADD shared/action-types.js /shared/action-types.js

# Add package.json again to include up to date version
ADD http-server/package.json /app/

ADD http-server/src /app/src
ADD http-server/config /app/config
ADD http-server/template /app/template
ADD http-server/static /app/static

EXPOSE 10000
CMD ["node", "--harmony_destructuring", "--harmony_default_parameters", "src/index.js"]
