rules:
  no-console: 0
  no-restricted-syntax:
    - 2
    - WithStatement
    # - ObjectPattern # object destructuring
    # - ArrayPattern # array destructuring
    - AssignmentPattern # default prama
    - RestElement # spread
    - SpreadElement # spread
