#!/usr/bin/env bash

# ------------------------------
# Start dev servers
# ------------------------------

(cd starboard-ui && npm run watch:build) &
(cd http-server && npm start) &
(cd http-server && ./scripts/start-browser-sync) &
(cd job-server  && npm start) &

wait
